### ISSUE TITLE
Request that getVariable function not affect Matlab environment

### ISSUE THREAD

**Issue by stefanavey** [HenrikBengtsson/R.matlab#13]
Just finished debugging a sneaky error.  I'm running a CVX model in Matlab many times it looks something like this:

```
tStart=tic
cvx_begin
    variable theta(100)
    minimize ( sum((1-y)'.*(theta'*X)) + sum( log_sum_exp( [zeros(1,m) -theta'*X]) ) + lambda1*norm(theta,1)+lambda2*theta'*L*theta )
cvx_end
```
The first time it would work perfectly and I could run the same code multiple times without any problems except if I tried to get some variables using the ```getVariable``` R function.  After calling ```getVariable``` evaluating the code above wouldn't work.

Turns out that a variable named ```variable``` was created in the Matlab environment by the function without me knowing and that caused the code to not work.  Probably won't affect most people who don't have variable definitions or use a variable named ```variable``` but is it possible to add some code to remove any variables created by the ```getVariable``` function?  I'm not sure if other functions in R.matlab do this too but especially for functions like ```getVariable``` that just get something from Matlab I did not expect the Matlab environment to change.  This might also affect people by writing over their variables so maybe there could be a warning if some variable ```variable``` already exists because it is getting written over.  I'm not sure what the best solution is but just wanted to bring it to your attention.

I fixed it in my case by just adding:
``` evaluate(matlab, "clear variable") ```

after my call to ```getVariable```

**Comment by HenrikBengtsson** [comment]
Thanks for reporting on this. I don't think `clear()`:ing variables will be the solution to this problem.  That would run the problem of removing MATLAB variables created by the user, although overwriting them is as bad.

A viable workaround is for the MATLAB server script to use variable names that are less likely to clash with the user.  I've created Issue #24 with details on that task.  I'm closing this issue since it's a special case of the new one.
