### ISSUE TITLE
Errors when empty data present in mat file

### ISSUE THREAD

**Issue by gordon-turner** [HenrikBengtsson/R.matlab#44]
I occasionally encounter .mat files saved from an instrument (powerlab) where the header contains information, but the data field is null.  readMat fails in those cases but can be rescued with a check for null data before converting to matrix for both character and text data types.  

Would it be possible to add in these two checks for empty data and set data = "" if character type, and NA if numeric?  This would happen at lines 1082 and 1098 in readMat.R

If possible, also add an explicit conversion to matrix before 1082 because sometimes I'm getting a character string that fails at the dim() call unless data is first converted to matrix.

**Comment by HenrikBengtsson** [comment]
@gordon-turner , thank you for this and the PR. I'd like to add a unit test for this too.  Do you think you could produce a teeny MAT file that triggers this problem/bug?  Then we could add it the existing set of MAT files (https://github.com/HenrikBengtsson/R.matlab/tree/develop/inst/mat-files)

**Comment by gordon-turner** [comment]
> 

Thank you @HenrikBengtsson.  I have added a test file to the PR and tried to add a test as well.  This is an odd file format that seems to have structures in it, yet is being referenced as a v4 file (which shouldn't have them).  I believe the instrument software is writing them directly, rather than coming from Matlab.  An alternate fix might be to somehow flag this as a v5 file and see if it can be read using the more modern file formatting, but for now this seems to solve my issue.  If you have suggestions, please let me know.

**Comment by HenrikBengtsson** [comment]
Thanks for this.  I think I have what I need for now.  Since your PR is a workaround for what looks like a faulty MAT write, I need to spend some time thinking about how to support this use case, without risking `readMat()` becoming a patch work.

Maybe it'll be supported by giving an informative error by default, but with an argument (e.g. `strict = FALSE`) and/or an R option (e.g. `options(R.matlab.readMat.strict = FALSE)` it can be read the way you propose.

BTW, and importantly, do you know how MATLAB handles this file?  What happens, and what does it return?

**Comment by gordon-turner** [comment]
Thanks.  I just tried opening it in MATLAB, and it opens with no errors.

**Comment by HenrikBengtsson** [comment]
> Thanks. I just tried opening it in MATLAB, and it opens with no errors.

Interesting.  So, maybe it's a valid MAT file at the end of the day, or MATLAB is just forgiving. I'll have to read up on the MATLAB file format specifications to see if it's handled there.

Exactly what type of data/object/value does it return where we now want to return a missing value? It's best if **R.matlab** tries to emulate what MATLAB does.

**Comment by gordon-turner** [comment]
There are two variables in this file that cause the problem. The first is a character string and MATLAB reads it in as a 0x0 empty char array.  The second is a numeric type and MATLAB reads it in as a 0x5 empty double matrix.  R.matlab appears to be reading in the lengths of these correctly in the header variable.

**Comment by HenrikBengtsson** [comment]
Ah, I see.  It's quite straightforward to create empty matrices in R, e.g.

```r
> data <- matrix(integer(0), nrow = 0L, ncol = 5L)
> data
     [,1] [,2] [,3] [,4] [,5]
```

The only somewhat tricky part is to get the data type correct, i.e. integer, numeric, logical, etc.  That's what the `storage.mode() <- ...` trick tries to solve.  However, we can actually leverage `header$what` for this, because that's already an empty vector of the data type we want create.

So, give that we end up with `is.null(data) == TRUE` in these special, cases, I suspect we can rewrite your current PR code:

```r
# Make into a matrix or an array
if (is.null(data)) {
  #check to support LabChart-created .mat files that don't adhere to file standards exactly
  data <- NA
  storage.mode(data) <- storage.mode(header$what)
} else {
  dim(data) <- c(header$mrows, header$ncols)
}
```

as

```r
## Special case: Empty MATLAB matrices are read as NULL, but
## we want an empty vector of the intended data type
if (is.null(data)) data <- header$what

dim(data) <- c(header$mrows, header$ncols)
```

Does that work?  If so, you can probably do something similar for the empty text matrix.

**Comment by gordon-turner** [comment]
That works well.  Simplifies the fix to only two lines of code and results in more faithful representation of what was in the original file.  Better matching of what MATLAB would return too.  Thank you!
